#!/usr/bin/python3
import argparse
import sys
import os
from datetime import datetime, timedelta 
import tempfile
import subprocess
import traceback

SCRIPT_PATH = os.path.abspath(__file__)
SCRIPT_NAME = os.path.basename(SCRIPT_PATH)
PROJECT_ROOT = os.path.dirname(SCRIPT_PATH)
UT_BIN_DIR = os.path.join(PROJECT_ROOT, 'tst/ut_bin')
LOGFILEPATH=os.path.join(PROJECT_ROOT,'validate.log')
LOGFILE = None
NO_TIMING = False
RUNINFOS = []

class strings:
    def section():
        return '---------------------------------------------------------------------------------'

    def separator():
        return '[----------] '
    
    def build():
        return '[ BUILD    ] '

    def run():
        return '[ RUN      ] '

    def ok():
        return '[       OK ] '

    def failed():
        return '[  FAILED  ] ' 

    def exception():
        return '[EXCEPTION ] '

def log(s, newline=True):
    global LOGFILE
    if isinstance(s, str):
        sys.stdout.write(s)
        LOGFILE.write(s)

        if newline:
            sys.stdout.write('\n')
            LOGFILE.write('\n')

        sys.stdout.flush()

def exscript(opname, lines, cwd=None, env=None):
    def execute(cmd, cwd=None, env=None):
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.PIPE, cwd=cwd, env=env)
        stdout = ''

        for line in process.stdout:
            fmt_line=str(line, 'utf-8')
            stdout+=fmt_line
            log(fmt_line, newline=False)
        
        stub_stdout, stderr = process.communicate()
        
        return process.returncode, stderr, stdout

    tmpfile = None
    code = None
    out = None
    err = None
   
    try:
        with tempfile.NamedTemporaryFile(mode='w+',delete=False) as file:
            tmpfile = file.name
            util_lines = [ \
                    'run() {', \
                    '    # Print the command to be executed', \
                    f'    echo "[{opname} execute] $1"', \
                    '    # Execute the command', \
                    '    eval "$1"', \
                    '    if [ $? -ne 0 ]; then', \
                    f'        echo "[{opname} ERROR] command failed"', \
                    '        exit 1', \
                    '    fi', \
                    '}', \
                    '']
            
            for line in util_lines:
                file.write(f'{line}\n')

            for line in lines:
                file.write(f'run "{line}"\n')

        code, out, err = execute(['bash',tmpfile], cwd=cwd, env=env)
    except Exception as e:
        if tmpfile is not None:
            os.remove(tmpfile)
        raise

    if tmpfile is not None:
        os.remove(tmpfile)

    return code, out, err

class RunInfo:
    name = None
    success = None
    runtime = None

    def __init__(self, name: str, success: bool, time):
        self.name = name
        self.success = success
        self.runtime = time

    def stringify(self):
        return f'<test:{self.name}, success:{self.success}, runtime:{self.runtime}>'

    def __repr__(self):
        return self.stringify()

    def __str__(self):
        return self.stringify()

def process_exit(success):
    global RUNINFOS
    log(strings.section())
    log('test run information:')

    for r in RUNINFOS:
        print(r)

    log('')
    
    if success == True:
        log('Test Validation Success')
        sys.exit(0)
    else:
        log('Test Validation FAILURE')
        sys.exit(1)

class Toolchain:
    cross = None

    def __init__(self, cross = ''):
        self.cross = cross

    def mapping(self):
        return {
            'gcc': f'-DCMAKE_C_COMPILER={self.cross}gcc -DCMAKE_CXX_COMPILER={self.cross}g++',
            'clang': f'-DCMAKE_C_COMPILER={self.cross}clang -DCMAKE_CXX_COMPILER={self.cross}clang++'
        }

class BuildType:
    RELEASE = '-DCMAKE_BUILD_TYPE=Release'
    DEBUG = '-DCMAKE_BUILD_TYPE=Debug'

class Timing:
    DISABLED = '-DTIME_SENSITIVE_TESTS_ENABLED=False'
    ENABLED = '-DTIME_SENSITIVE_TESTS_ENABLED=True'

class Optimization:
    LOW = '-Og -fno-inline'
    HIGH = '-O3'

class Concurrency:
    CONCURRENT = '-DHCETHREADPOOLSCHEDULERCOUNT=1'
    PARALLEL = '-DHCETHREADPOOLSCHEDULERCOUNT=0'

class Log:
    RELEASE = '-DHCELOGLEVEL=-1 -DHCELOGLIMIT=-1'
    INFO = '-DHCELOGLEVEL=0 -DHCELOGLIMIT=0'
    MAX = '-DHCELOGLEVEL=9 -DHCELOGLIMIT=9'

class AddressSanitation:
    DISABLED = ''
    ENABLED = '-fsanitize=address'

class Option:
    value = None

    def __init__(self, value=None):
        self.value = value 

    def __bool__(self):
        if self.value is not None:
            return True
        else:
            return False

    def __str__(self):
        return str(self.value)

def validate_attr(attribute, attribute_name):
    if attribute is None:
        raise Exception(f'{attribute_name} is None')

class Build:
    name = Option()
    toolchain = Option()
    buildtype = Option()
    timing = Option()
    log = Option()
    optimization = Option()
    concurrency = Option()
    address_sanitation = Option()

    def __init__(self, name: str, cross: str, toolchain_name: str, buildtype: BuildType, timing: Timing, log: Log, optimization: Optimization, concurrency: Concurrency, address_sanitation: AddressSanitation):
        toolchain = None 
        if toolchain_name in Toolchain(cross).mapping():
            toolchain = Toolchain(cross).mapping()[toolchain_name]

        global SCRIPT_NAME
        self.name = f'{SCRIPT_NAME}.{toolchain_name}.{name}'
        self.toolchain = Option(toolchain)
        self.buildtype = Option(buildtype)

        global NO_TIMING
        if NO_TIMING:
            self.timing = Option(Timing.DISABLED)
        else:
            self.timing = Option(timing)

        self.log = Option(log)
        self.optimization = Option(optimization)
        self.concurrency = Option(concurrency)
        self.address_sanitation = Option(address_sanitation)

    def __str__(self):
        return f'\n\tname: {self.name}\n\ttoolchain: {self.toolchain}\n\tbuildtype: {self.buildtype}\n\ttiming: {self.timing}\n\tlog: {self.log}\n\toptimization: {self.optimization}\n\tconcurrency: {self.concurrency}\n\taddress_sanitation: {self.address_sanitation}\n'

    def commands(self):
        return [ \
            'cmake {} {} {} {} {} -DCMAKE_CXX_FLAGS=\\"{} {}\\" .'.format( \
                str(self.toolchain), \
                str(self.buildtype), \
                str(self.timing), \
                str(self.log), \
                str(self.concurrency), \
                str(self.optimization), \
                str(self.address_sanitation)), \
            'make -j hce_ut']

    @staticmethod
    def validate(attribute, attribute_name):
        if attribute is None:
            raise Exception(f'Option {attribute_name} is None')

    def __call__(self, env=os.environ):
        validate_attr(self.name, 'name')
        validate_attr(self.toolchain, 'toolchain')
        validate_attr(self.buildtype, 'buildtype')
        validate_attr(self.timing, 'timing')
        validate_attr(self.log, 'log')
        validate_attr(self.optimization, 'optimization')
        validate_attr(self.concurrency, 'concurrency')
        validate_attr(self.address_sanitation, 'address_sanitation')
        global PROJECT_ROOT 
        code, _, _ = exscript(self.name, self.commands(), cwd=PROJECT_ROOT, env=env)

        if code != 0:
            raise Exception(f'Build {self.name} failed, return code:{code}')
            
        log(strings.ok())

class Test:
    build = None 
    name = ''
    testrunner = None

    def __init__(self, build: Build, testrunner = None):
        self.build = build
        self.name = build.name 
        self.testrunner = None

    def __str__(self):
        return f'{self.build}'
    
    def __call__(self, env=os.environ):
        validate_attr(self.name, 'name')
        start = datetime.now()
        success = False

        try:
            global UT_BIN_DIR
            log(strings.build() + str(self.name))
            self.build(env=env)
            ut_path = f'{UT_BIN_DIR}/hce_ut'
            commands = list()

            if(self.testrunner):
                commands.append(f'{self.testrunner} {UT_BIN_DIR} {ut_path}')
            else:
                commands.append(f'{ut_path}')

            log(strings.separator())
            log(strings.run() + str(self.name))
            code, _, _ = exscript(self.name, commands, cwd=PROJECT_ROOT, env=env)

            if code != 0:
                raise Exception(f'Test {self.name} failed, return code:{code}')

            log(strings.ok())
            success = True
        except Exception as e:
            traceback.print_exc()
            log(strings.failed())
            log(strings.exception() + str(e))
            success = False

        now = datetime.now()
        global RUNINFOS
        RUNINFOS.append(RunInfo(self.build.name, success, now - start))

# Really put the framework through its paces by introducing runtime timing 
# discrepancies with various loglevels and loglimits. 
# 
# This operation is to tease out timing issues, and it is unknown high or low 
# optimization would trigger them.
class jitterTest:
    name = None 
    cross = None
    toolchain = None 
    buildtype = None
    optimization = None 

    def GetTest(self, loglimit, loglevel):
        return Test(Build(self.name, self.cross, self.toolchain, self.buildtype, Timing.DISABLED, f'-DHCELOGLEVEL={loglevel} -DHCELOGLIMIT={loglimit}', self.optimization, Concurrency.PARALLEL, AddressSanitation.DISABLED))

    def __init__(self, name, cross, toolchain, buildtype, optimization):
        self.name = name 
        self.cross = cross
        self.toolchain = toolchain
        self.buildtype = buildtype
        self.optimization = optimization

    def __str__(self):
        exampletest = self.GetTest(-1,-1)
        return f' introduce timing variation by iteratively testing loglimit -1 to 9 and loglevel -1 to 9, with a test similar to: {exampletest}'

    def __call__(self):
        for loglimit in range(-1, 10):
            for loglevel in range(-1, 10):
                test = self.GetTest(loglimit, loglevel)
                test() # rebuild and execute test

class Tests:
    basic = None
    parallel = None
    log = None
    mem = None 
    jitter = None
    performance = None
    release = None
    tests = None 

    def __init__(self, cross='', toolchain_name=''):
        self.basic = Test(Build('basic', cross, toolchain_name, BuildType.DEBUG, Timing.ENABLED, Log.INFO, Optimization.LOW, Concurrency.CONCURRENT, AddressSanitation.DISABLED))
        self.parallel= Test(Build('parallel', cross, toolchain_name, BuildType.DEBUG, Timing.ENABLED, Log.INFO, Optimization.LOW, Concurrency.PARALLEL, AddressSanitation.DISABLED))
        self.log = Test(Build('log', cross, toolchain_name, BuildType.DEBUG, Timing.DISABLED, Log.MAX, Optimization.LOW, Concurrency.CONCURRENT, AddressSanitation.DISABLED))
        self.mem = Test(Build('mem', cross, toolchain_name, BuildType.DEBUG, Timing.ENABLED, Log.INFO, Optimization.LOW, Concurrency.CONCURRENT, AddressSanitation.ENABLED))
        self.jitter = jitterTest('jitter', cross, toolchain_name, BuildType.DEBUG, Optimization.LOW)
        self.performance = Test(Build('performance', cross, toolchain_name, BuildType.RELEASE, Timing.ENABLED, Log.RELEASE, Optimization.HIGH, Concurrency.PARALLEL, AddressSanitation.DISABLED))
        self.release = Test(Build('release', cross, toolchain_name, BuildType.RELEASE, Timing.ENABLED, Log.RELEASE, Optimization.HIGH, Concurrency.CONCURRENT, AddressSanitation.DISABLED))

        self.tests = {
            'basic': self.basic,
            'parallel': self.parallel,
            'log': self.log,
            'mem': self.mem,
            'jitter': self.jitter,
            'performance': self.performance,
            'release': self.release
        }

    def ALL(self):
        # Create a function that runs all tests in sequence
        def run_all_tests():
            for name, test in self.tests.items():
                test.value()
        return run_all_tests()  # Call the function here 

    def names(self):
        results = list()
        results.append('info')

        for name, test in self.tests.items():
            results.append(name)

        results.append('ALL')

        return results

    def infos(self):
        results = list()

        for name, test in self.tests.items():
            results.append(f'{name}:{test}')

        results.append('ALL: execute all of the above tests in sequence, useful as a deep validation of the implementation')

        return results

def parse_args():
    parser = argparse.ArgumentParser('A validation script for running HCE project unit tests.')

    # Top-level parser with required compiler argument
    subparsers = parser.add_subparsers(dest="compiler", required=True, help='Specify a toolchain')

    def add_subparser(name):
        parser = subparsers.add_parser(name, help=f"Options for {name} compiler toolchain. The test \'info\' will print detailed information about available tests.")
        parser.add_argument("test", choices=Tests().names(), help="Select a test to run")
        parser.add_argument("--no-timing", action='store_true', help="Disable timing tests")
        parser.add_argument("--cross-compile", default='', help="Optionally specify a CROSS_COMPILE style prefix which will be applied to the given toolchain")
        parser.add_argument("--test-runner", default=None, help="Optionally specify a script or binary to pass built unit tests to. This argument should accept 2 arguments (the full path to the directory of built unit test binaries, all need to be copied to an executing environment if its elsewhere, and the full path to the unit test binary). The script should execute the unit test binary and return its exit code. This mechanism provides a way to execute unit tests built with --cross-compile on the target hardware (IE, copying the files to the target hardware and executing it there then returning the result to validate)")

    add_subparser('gcc')
    add_subparser('clang')

    args = parser.parse_args()

    if args.no_timing:
        global NO_TIMING
        NO_TIMING = True

    return args

def main():
    def inner():
        args = parse_args()

        if(args.test == 'info'):
            log('HCE Test Information')
            infos = Tests(args.cross_compile, args.compiler).infos()

            for info in infos:
                log(info)

            return 0
        else:
            test = Tests(args.cross_compile, args.compiler).tests[args.test]
            log(strings.section())
            test()

            global RUNINFOS
            log(strings.section())
            log('Test Report')
            log(strings.separator())
            success = True

            for r in RUNINFOS:
                success = success and r.success
                print(r)

            log('')
            
            if success == True:
                log('HCE Test Validation SUCCESS')
                return 0
            else:
                log('HCE Test Validation FAILURE')
                return 1

    # setup the logfile so log() can function
    global LOGFILEPATH
    code = 0

    try:
        # remove old logs 
        os.remove(LOGFILEPATH)
    except FileNotFoundError:
        # silent continuation if the file doesn't exist
        pass  

    with open(LOGFILEPATH, 'a') as logfile:
        global LOGFILE 
        LOGFILE = logfile 
        global SCRIPT_NAME
        log(f'logfile:{LOGFILEPATH}')
        code = inner()

    sys.exit(code)

if __name__ == '__main__':
    main()
