//SPDX-License-Identifier: MIT
//Author: Blayne Dennis 
#ifndef HERMES_COROUTINE_ENGINE_SCHEDULER
#define HERMES_COROUTINE_ENGINE_SCHEDULER

// c++
#include <cstddef>
#include <cstdlib>
#include <memory>
#include <mutex>
#include <condition_variable>
#include <exception>
#include <list>
#include <string>
#include <sstream>
#include <thread>

// local 
#include "base.hpp"
#include "logging.hpp"
#include "utility.hpp"
#include "service.hpp"
#include "atomic.hpp"
#include "memory.hpp"
#include "alloc.hpp"
#include "thread.hpp"
#include "list.hpp"
#include "coroutine.hpp"
#include "awaitable.hpp"

namespace hce {
namespace config {
namespace scheduler {

/**
 @brief object for configuring runtime behavior of a `scheduler`

 An instance of this object passed to `scheduler::make()` will configure 
 the scheduler during its runtime with the given event handlers and options.

 Unless the user manually creates new schedulers with `scheduler::make()`, 
 then most instances of `config` will be generated by 
 `hce::config::global::scheduler_config()` (and 
 `hce::config::threadpool::scheduler_config()`) when the framework is 
 constructing managed `scheduler`s. Said functions are `extern`and can be 
 overridden if `cmake` is configured with the `HCECUSTOMCONFIG` definition, 
 requiring the user to link their own implementation.
 */
struct config {
    config();

    /**
     Set the log level of the thread the scheduler is installed on.

     Maximum value: 9
     Minimum value: -9
     */
    int loglevel;

    /**
     The count of coroutine handles the scheduler can pool for reuse 
     without deallocating. A sane value (roughly equal or above the median count 
     of executing coroutines during busy periods) allows avoiding unnecessary 
     re-allocation of handles during normal operation. 

     This only potentially affects the scheduler's throughput processing 
     efficiency, it has no effect on the underlying coroutine execution.

     Handles are very small allocations (pointer sized). They are allocated 
     separately from the underlying coroutine itself.
     */
    size_t reusable_coroutine_handle_cache;
};

namespace global {

/**
 @brief provide the global scheduler configuration

 This `config` is used when constructing the process wide, default `scheduler` 
 (IE, the `scheduler` returned from 
 `scheduler::global::service::get().scheduler()`).

 @return a copy of the global scheduler configuration 
 */
hce::config::scheduler::config config();

}

}
}

struct scheduler;

struct scheduler_halted_exception : public std::exception {
    scheduler_halted_exception(scheduler* sch) : 
        estr([&]() -> std::string {
            std::stringstream ss;
            ss << "schedule() failed because scheduler is halted:" << sch;
            return ss.str();
        }())
    { }

    inline const char* what() const noexcept { return estr.c_str(); }

private:
    const std::string estr;
};

struct awaitable_destroyed_without_joining_result : public std::exception {
    awaitable_destroyed_without_joining_result(void* c, void* j) :
        estr([&]() -> std::string {
            std::stringstream ss;
            ss << "std::coroutine_handle<>@" 
               << (void*)c
               << " was destroyed before it was completed, so " 
               << (hce::printable*)j
               << " cannot join with it";
            return ss.str();
        }()) 
    { }

    inline const char* what() const noexcept { return estr.c_str(); }

private:
    const std::string estr;
};

namespace detail {
namespace scheduler {

/*
 An implementation of hce::awt<T>::interface capable of joining a coroutine 

 Requires implementation for awaitable::interface::destination().
 */
template <typename T>
struct joiner : 
    public hce::awaitable::spinlock_lockable<typename hce::awt<T>::interface>
{
    joiner(hce::co<T>& co) :
        hce::awaitable::spinlock_lockable<
            typename hce::awt<T>::interface>(
                hce::awaitable::await::policy::defer_lock,
                hce::awaitable::resumed::policy::unlocked,
                hce::awaitable::resume::policy::lock),
        address_(co.address())
    { 
        HCE_TRACE_CONSTRUCTOR(co);

        // install a cleanup handler to resume the returned awaitable when 
        // the coroutine goes out of scope 
        hce::get_promise(co).install(&joiner<T>::cleanup, this);
    }

    virtual ~joiner(){}

    static inline std::string info_name() { 
        return type::templatize<T>("hce::detail::scheduler::joiner"); 
    }

    inline std::string name() const { return joiner<T>::info_name(); }
    inline void* address() const { return address_; }

    inline void on_resume(void* m) { 
        HCE_TRACE_METHOD_ENTER("on_resume",m);
        this->ready(true);

        if(m) [[likely]] { 
            // move the unique pointer from the promise to this object
            hce::unique_ptr<T>* result = static_cast<hce::unique_ptr<T>*>(m);
            t_ = std::move(*result); 
        } 
    }

    inline T get_result() { 
        if(!t_) [[unlikely]] { 
            throw awaitable_destroyed_without_joining_result(address_, this); 
        }

        return std::move(*t_); 
    }

private:
    /*
     The purpose of joiner<T>::cleanup is to act as a connector between a 
     co<T>'s promise_type, which contains the result of `co_return`, and the 
     awaitable (an allocated instance of joiner<T>) returned by 
     `scheduler::schedule()`, which needs the result of `co_return`. This 
     handler is triggered just before the promise_type is destroyed and passes 
     around the necessary data to the awaitable (joiner<T>) and resumes it.
     */
    static inline void cleanup(hce::cleanup::data& data) { 
        HCE_TRACE_FUNCTION_ENTER(hce::detail::scheduler::joiner<T>::info_name() + "::cleanup", data.install, data.self);
        // acquire a reference to the joiner<T>
        auto& joiner = *(static_cast<hce::detail::scheduler::joiner<T>*>(data.install));

        // acquire a reference to the promise
        auto& promise = *(static_cast<typename hce::co<T>::promise_type*>(data.self));

        // get a copy of the handle to see if the coroutine completed 
        auto handle = std::coroutine_handle<hce::co_promise_type<T>>::from_promise(promise);

        if(handle.done()) [[likely]] {
            //HCE_MIN_FUNCTION_BODY("joiner<T>::cleanup()","done@",handle);
            HCE_TRACE_FUNCTION_BODY(hce::detail::scheduler::joiner<T>::info_name() + "::cleanup","done@",handle);
            // resume the blocked awaitable and pass the allocated result pointer
            joiner.resume(&(promise.result));
        } else [[unlikely]] {
            HCE_ERROR_FUNCTION_BODY(hce::detail::scheduler::joiner<T>::info_name() + "::cleanup","NOT done@",handle);
            // resume with no result, presumably triggering error
            joiner.resume(nullptr);
        } 
    };

    void* address_;
    hce::unique_ptr<T> t_;
};

// joiner variant for coroutine returning void 
template <>
struct joiner<void> : 
    public hce::awaitable::spinlock_lockable<typename hce::awt<void>::interface>
{
    joiner(hce::co<void>& co) :
        hce::awaitable::spinlock_lockable<
            typename hce::awt<void>::interface>(
                hce::awaitable::await::policy::defer_lock,
                hce::awaitable::resumed::policy::unlocked,
                hce::awaitable::resume::policy::lock),
        address_(co.address())
    { 
        HCE_TRACE_CONSTRUCTOR(co);

        hce::get_promise(co).install(&joiner<void>::cleanup, this);
    }

    virtual ~joiner(){}
    
    static inline std::string info_name() { 
        return type::templatize<void>("hce::detail::scheduler::joiner"); 
    }

    inline std::string name() const { return joiner<void>::info_name(); }
    inline void* address() const { return address_; }
    inline void on_resume(void* m) { this->ready(true); }

private:
    static inline void cleanup(hce::cleanup::data& data) { 
        HCE_TRACE_FUNCTION_ENTER("joiner<void>::cleanup()", data.install, data.self);
        static_cast<hce::detail::scheduler::joiner<void>*>(data.install)->resume(nullptr);
    }

    void* address_;
};

}
}

/** 
 @brief object responsible for scheduling and executing coroutines
 
 A scheduler` cannot be created directly, it must be created by calling 
 `hce::scheduler::make()`.

 `scheduler` API, unless otherwise specified, is threadsafe and coroutine-safe.
 That is, it can be called from anywhere safely, including from within a 
 coroutine running on the scheduler which is being accessed.

 `scheduler`s run independently on their own system threads. However, their 
 lifecycle is controlled and synchronized through a globally accessible 
 `lifecycle::service` object. This object allows the user to suspend and resume
 execution of coroutines as necessary, and is responsible for ensuring that
 schedulers properly halt when the process exits, taking into account 
 non-deterministic runtime behavior of scheduled coroutines.
*/
struct scheduler : public printable {
    /// an enumeration which represents the scheduler's current state
    enum state {
        executing, /// scheduler is executing coroutines
        suspended, /// execution paused by a call to `lifecycle::suspend()`
        halted /// scheduler is completely halted
    };
   
    template <typename T>
    struct null_coroutine_exception : public std::exception {
        null_coroutine_exception(hce::co<T>* c) :
            estr([&]() -> std::string {
                std::stringstream ss;
                ss << "cannot schedule empty coroutine: " << c;
                return ss.str();
            }())
        { }

        inline const char* what() const noexcept { return estr.c_str(); }

    private:
        const std::string estr;
    };
   
    template <typename T>
    struct done_coroutine_exception : public std::exception {
        done_coroutine_exception(hce::co<T>* c) :
            estr([&]() -> std::string {
                std::stringstream ss;
                ss << "cannot schedule done coroutine: " << c;
                return ss.str();
            }())
        { }

        inline const char* what() const noexcept { return estr.c_str(); }

    private:
        const std::string estr;
    };

    /**
     @brief partial implementation of awaitable::interface allowing rescheduling 

     Awaitables implementing this will schedule coroutine on a parent scheduler 
     when an awaitable implementation is resumed. 
     
     This implements `on_suspend()` and `to_destination()` API.
     */
    template <typename INTERFACE>
    struct reschedule : public INTERFACE {
        /// framework selects the scheduler to reschedule on
        template <typename... As>
        reschedule(As&&... as) : 
            INTERFACE(std::forward<As>(as)...) 
        { }

        virtual ~reschedule(){}
       
        /// acquire the destination
        inline void on_suspend() {
            /* 
             Now that we're suspending we know to try and acquire a 
             destination. If we're not in a scheduler then we're going to block 
             on the thread_local condition variable and destination() won't be 
             called.
             */
            this->destination_ = hce::scheduler::ptr();
        }

        /// pass a resumed coroutine to its destination
        inline void to_destination(std::coroutine_handle<> h) {
            HCE_LOW_METHOD_ENTER("to_destination",h);
            this->destination_->schedule_(std::move(h));
        }

    private:
        hce::scheduler* destination_ = nullptr;
    };

    /**
     @brief complete awaitable capable of rescheduling the awaiting coroutine on another scheduler

     This awaitable is slightly different from most awaitables in this framework 
     because it does not inherit hce::awaitable. Instead, it is a direct 
     implementation of what the compiler requires for it to be considered an 
     awaitable.
     */
    struct migrater : public printable {
        migrater(hce::scheduler& destination) : destination_(&destination) {
            HCE_LOW_CONSTRUCTOR();
        }

        virtual ~migrater() { HCE_LOW_DESTRUCTOR(); }

        static inline std::string info_name() { return "hce::scheduler::migrater"; }
        inline std::string name() const { return migrater::info_name(); }

        inline bool await_ready() { 
            HCE_MIN_METHOD_ENTER("await_ready");

            if(hce::scheduler::in()) [[likely]] {
                return false;
            } else [[unlikely]] {
                return true;
            }
        }

        inline void await_suspend(std::coroutine_handle<> h) {
            HCE_MIN_METHOD_ENTER("await_suspend");
            coroutine::local().release(); 
            destination_->schedule_(std::move(h));
        }

        inline void await_resume() { 
            HCE_MIN_METHOD_ENTER("await_resume");
        }

    private: 
        hce::scheduler* destination_ = nullptr;
    };

    /**
     @brief a complete awaitable interface capable of joining with a coroutine  

     An allocated instance of this object can be passed to 
     `hce::awt<T>()` and awaited. 

     One potential usecase for this mechanism is to await a coroutine that is 
     being executed *outside* an `hce::scheduler`. It is used internally in all 
     `hce::scheduler::schedule()` operations.
     */
    template <typename T>
    struct joiner : 
        public hce::scheduler::reschedule<hce::detail::scheduler::joiner<T>> 
    { 
        /**
         Join the coroutine and resume any suspended coroutine on a selected
         scheduler
         */
        joiner(hce::co<T>& co) :
            hce::scheduler::reschedule<hce::detail::scheduler::joiner<T>>(co)
        { 
            HCE_MIN_CONSTRUCTOR(co);
        }

        virtual ~joiner() { 
            HCE_MIN_DESTRUCTOR(); 
            this->clean();
        }

        static inline std::string info_name() { 
            return type::templatize<T>("hce::scheduler::joiner"); 
        }

        inline std::string name() const { return joiner<T>::info_name(); }

        inline std::string content() const {
            std::stringstream ss;
            ss << std::coroutine_handle<>::from_address(this->address());
            return ss.str();
        }
    };

    /**
     @brief object controlling the lifecycle of a scheduler 

     A lifecycle object manages both the scheduler instance and the thread it is 
     running on. When this object goes out of scope both are shutdown and 
     joined.
     */
    struct lifecycle : public printable {
        /**
         @brief process-wide object responsible for managing scheduler lifecycles
         */
        struct manager : public hce::service<manager>, public hce::printable {
            manager();
            virtual ~manager();
            static std::string info_name();
            std::string name() const;
            std::string content() const;

            /**
             @brief register a lifecycle pointer to be destroyed at process exit
             */
            void registration(std::unique_ptr<scheduler::lifecycle> lptr);

            /*
             @brief temporarily suspend all registered running schedulers executing coroutines
             */
            void suspend();

            /**
             @brief resume coroutine execution on all registered schedulers after a call to `suspend()`
             */
            void resume();

        private:
            hce::spinlock lk_;
            hce::scheduler::state state_;

            // it is important that the lifecycles are destroyed last, so this
            // list is declared first (destructors are called first-in-last-out)
            std::list<std::unique_ptr<scheduler::lifecycle>> lifecycle_pointers_;

            friend hce::lifecycle;
        };

        /**
         @brief shutdown the scheduler
         */
        virtual ~lifecycle();

        static std::string info_name();
        std::string name() const;
        std::string content() const;

        /**
         @return a reference to the `lifecycle`'s associated scheduler
         */
        hce::scheduler& get_scheduler();

        /*
         @brief temporarily suspend the scheduler from executing coroutines

         A suspended scheduler will cease processing coroutines until either 
         resume() is called or the `lifecycle` goes out of scope.
         */
        void suspend();

        /**
         @brief resume coroutine execution on the scheduler after a call to `suspend()`
         */
        void resume();

    private:
        lifecycle() = delete;
        lifecycle(lifecycle&&) = delete;
        lifecycle(const lifecycle&) = delete;
        lifecycle& operator=(lifecycle&&) = delete;
        lifecycle& operator=(const lifecycle&) = delete;

        lifecycle(std::shared_ptr<hce::scheduler> sch);

        std::shared_ptr<hce::scheduler> sch_;
        std::thread thd_;
        friend hce::scheduler;
    };

    /**
     @brief the object managing the process-wide global scheduler instance
     */
    struct global : public hce::service<global>, public hce::printable {
        virtual ~global();
        static std::string info_name();
        std::string name() const;

        /// return the process-wide scheduler instance
        hce::scheduler& get_scheduler();

    private:
        global();
        hce::scheduler& sch_;
        friend hce::lifecycle;
    };

    virtual ~scheduler();
    static std::string info_name();
    std::string name() const;

    /**
     @brief allocate, construct and run a scheduler on a new system thread

     Allocates and registers a new `scheduler` and its `lifecycle` object.

     `scheduler::make()` calls are the only way to make a new scheduler. The 
     returned allocated `std::unique_ptr<scheduler::lifecycle>` contains the new 
     scheduler. Said scheduler can be retrieved as a reference by calling method 
     `lifecycle::scheduler()`. 

     Unless there is a very pressing reason, a scheduler accessed with 
     `hce::schedule()` or via the threadpool with `hce::threadpool::schedule()` 
     should be sufficient for user needs. Therefore it is unlikely a user will 
     need to manually call this function.

     @param c optional config unique pointer to configure the runtime behavior of the scheduler
     @return an allocated lifecycle unique pointer containing the scheduler shared pointer
     */
    static std::unique_ptr<lifecycle> make(hce::config::scheduler::config c = {});

    /**
     This can only return `true` when called by a code evaluating in a coroutine 
     scheduled on the the scheduler.

     @return `true` if calling thread is executing an installed scheduler, else `false`
     */
    static bool in();

    /**
     @brief retrieve the calling thread's running scheduler 

     WARNING: it is an ERROR to call this function when if 
     `scheduler::in() == false`

     @return a scheduler reference
     */
    static scheduler& local();

    /**
     @brief retrieve the pointer to the calling thread's scheduler (may be null)

     For general usage it is recommended to use hce::scheduler::in() to 
     determine if hce::scheduler::local() is valid instead of directly acquiring 
     the pointer for clarity reasons. However, as a micro-optimization, the 
     pointer can be directly acquired here.
     */
    static scheduler* ptr();

    /**
     @brief retrieve some running scheduler

     Prefer `scheduler::local()`, falling back to `scheduler::global::serviec`.

     Useful when some scheduler is required, but a specific scheduler is not. 
     Additionally, operating on the current thread's scheduler (with 
     `scheduler::local()`), where possible, mitigates inter-thread communication 
     delays. Hence, this is a useful function for building generic higher level 
     operations which require scheduling.

     @return a scheduler reference
     */
    static scheduler& get();

    /// compare two schedulers, equality is always memory address equality
    bool operator==(const scheduler& rhs) const;
    
    /// contrast two schedulers, inequality is always memory address inequality
    bool operator!=(const scheduler& rhs) const;

    /// return a copy of this scheduler's shared pointer by conversion
    operator std::shared_ptr<scheduler>();

    /// return a copy of this scheduler's weak pointer by conversion
    operator std::weak_ptr<scheduler>();
    
    /**
     @return the scheduler thread's log level
     */
    int loglevel() const;

    /// return the state of the scheduler
    state status() const;

    /**
     @brief access a heuristic for the scheduler's active workload 

     This value only accounts for actively scheduled coroutines executing or 
     waiting to execute. block() worker threads and blocked (awaiting) 
     coroutines are not considered.

     @return the count of coroutines executing and waiting to execute
     */
    size_t scheduled_count() const;

    /**
     @return the configuration of the scheduler
     */
    const hce::config::scheduler::config config();

    /***
     @brief schedule a single coroutine and return an awaitable to await the `co_return`ed value

     `void` is a valid return type for the given `hce::co<T>` (`hce::co<void>`), 
     in which case the returned awaitable should be called with `co_await` but 
     no value shall be assigned from the result of the statement.

     Scheduling order is not guaranteed to be FIFO (first in, first out). This 
     is not because of a piority mechanism, but because scheduling is done 
     based on throughput efficiency and *not* ordering. This includes using 
     lockless batch scheduling, which may incidentally cause coroutines to 
     execute out of order. Ordering can be enforced by using awaitable 
     mechanisms to block coroutines and synchronize operations.

     @param co a coroutine to schedule
     @return an awaitable which when `co_await`ed will join with and return the result of the completed coroutine
     */
    template <typename T>
    inline hce::awt<T> schedule(hce::co<T> co) {
        HCE_HIGH_METHOD_ENTER("schedule",co);
        hce::awt<T> awt;

        if(co) [[likely]] {
            if(co.done()) [[unlikely]] {
                throw done_coroutine_exception(&co);
            } else [[likely]] {
                auto j = new hce::scheduler::joiner<T>(co);

                // returned awaitable resumes when the coroutine handle is destroyed 
                awt = hce::awt<T>(j);
                schedule_(co.release());
            }
        } else [[unlikely]] {
            throw null_coroutine_exception(&co);
        }

        return awt;
    }

    /**
     When this awaitable returns from being `co_await`ed, the calling coroutine 
     will be executing on this scheduler.

     WARNING: awaiting the returned awaitable from a system thread will do 
     nothing.

     @return an awaitable capable of migrating the awaiting coroutine to this scheduler 
     */
    migrater migrate();
 
private:
    scheduler(const hce::config::scheduler::config& cfg);

    // finish initializing and configuring the scheduler
    void finalize_(std::shared_ptr<scheduler>& self);

    // handle validation is done at a higher level
    void schedule_(std::coroutine_handle<> h);

    /*
     Suspend the scheduler. 

     Pauses operations on the scheduler and causes calls to run() to return 
     early.
     */
    void suspend_();

    /*
     Resumes a suspended scheduler. 
     */
    void resume_();

    /*
     Initialize the halt process in the scheduler. After this is called the 
     scheduler will begin communicating with the `lifecycle::service` to 
     negotiate a clean halted of the process.

     This operation ends all current and future coroutine execution on the 
     scheduler. However, this will not return until all previously scheduled 
     coroutines are completed.
     */
    void halt_();

    /* 
     Reset scheduler state flags, etc. Does not reset scheduled coroutine 
     queues. 
    
     This method can ONLY be safely called by the constructor or run() because 
     access to these values is always unsynchronized.
     */
    void reset_flags_();
 
    // notify caller of run() that resume() has been called 
    void resume_notify_();
   
    /* 
     Notify caller of run() that operations are potentially available and 
     state needs to be rechecked.
     */
    void coroutines_notify_();

    /*
     Execute coroutines continuously. This processing loop is highly optimized, 
     and contains a variety of comments to explain its design.

     It is an ERROR if this is called inside another scheduler. 

     It is an ERROR if this is called more than once by a scheduler.
     */
    void run();

    // synchronization primative, marked mutable for use in const methods.
    mutable hce::spinlock lk_;

    // the scheduler configuration
    const hce::config::scheduler::config config_;

    // the current lifecycle state of the scheduler
    state state_; 
                  
    // the count of actively executing coroutines in this scheduler's run()
    size_t batch_size_; 

    // flag for when scheduler::resume() is called
    bool waiting_for_resume_;
    
    // flag for when scheduled operation state changes
    bool waiting_for_coroutines_; 
  
    // condition for when scheduler::resume() is called
    std::condition_variable_any resume_cv_;

    // condition for when scheduled operation state changes
    std::condition_variable_any coroutines_cv_;

    // Queue holding scheduled coroutine handles. Simpler to just use underlying 
    // std::coroutine_handle than to utilize conversions between 
    // hce::coroutine and hce::co<T>. This object is a unique_ptr because it is 
    // routinely swapped between this object and the stack memory of the caller 
    // of scheduler::run() as a batch processing optimization.
    std::unique_ptr<hce::list<std::coroutine_handle<>>> coroutine_queue_;

    // a weak_ptr to the scheduler's shared memory
    std::weak_ptr<scheduler> self_wptr_;
};

/**
 @brief call schedule() on a scheduler
 @param as arguments for scheduler::schedule()
 @return result of scheduler::schedule()
 */
template <typename... As>
inline auto schedule(As&&... as) {
    HCE_HIGH_FUNCTION_ENTER("hce::schedule");
    return scheduler::get().schedule(std::forward<As>(as)...);
}

}

#endif
